# Generated by Django 4.0.6 on 2023-10-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=11),
        ),
    ]
